services:
  - type: web
    name: financial-valuation-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: user
        value: postgres.lziabrglyusvzdlywyno
      - key: password
        value: 181841thi181841
      - key: host
        value: aws-0-sa-east-1.pooler.supabase.com
      - key: port
        value: 5432
      - key: dbname
        value: postgres

  - type: static_site
    name: financial-valuation-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: VITE_API_BASE_URL
        value: https://financial-valuation-backend.onrender.com/api/v1
