services:
  - type: web
    name: financial-valuation-backend
    env: docker
    rootDir: backend
    dockerfilePath: Dockerfile
    envVars:
      - key: DB_HOST
        value: aws-0-sa-east-1.pooler.supabase.com
      - key: DB_PORT
        value: "5432"
      - key: DB_USER
        value: postgres.lziabrglyusvzdlywyno
      - key: DB_PASSWORD
        value: 181841thi181841
      - key: DB_NAME
        value: postgres
      # Adicione aqui outras variáveis que seu app precise, ex:
      # - key: SECRET_KEY
      #   value: <sua_secret_key>
      # - key: SUPABASE_URL
      #   value: https://lziabrglyusvzdlywyno.supabase.co
      # - key: SUPABASE_ANON_KEY
      #   value: <anon-key>
