services:
  # Backend - Web Service Dinâmico
  - type: web
    name: financial-valuation-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 --threads 2 -b 0.0.0.0:$PORT main:app"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9" # <--- ALTERE O VALOR AQUI
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: FLASK_DEBUG
        value: "False"

  # Frontend - Site Estático
  - type: web
    name: financial-valuation-frontend
    env: static
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    autoDeploy: true
