services:
  - type: web
    name: financial-valuation-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 --threads 2 -b 0.0.0.0:$PORT main:app"
    autoDeploy: true
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: FLASK_DEBUG
        value: "False"
  - type: web
    name: financial-valuation-frontend
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    autoDeploy: true
    plan: free
