services:
  - type: web
    name: financial-valuation-backend
    env: docker
    rootDir: backend
    dockerfilePath: Dockerfile
    envVars:
      - key: user
        value: postgres.lziabrglyusvzdlywyno
      - key: password
        value: 181841thi181841
      - key: host
        value: aws-0-sa-east-1.pooler.supabase.com
      - key: port
        value: 5432
      - key: dbname
        value: postgres
